Fixes for Z88DK
lure-sh/lure-repo pull request #54
Opened 2023-10-15 14:54 UTC by atirut-w

- Specify a known good commit
- Correct build script

Additional testing by third parties would be appreciated 👍.

2023-10-16 17:45 UTC, Elara6331 requested changes

2023-10-16 17:45 UTC, Elara6331 commented on z88dk-git/lure.sh
> +	eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
This can be moved to a separate prepare function before the build step, and it should put the local-lib in srcdir so that it doesn't affect the system environment.

It would look like this:

```
prepare() {
	cpanm --local-lib="$srcdir/perl5" App::Prove CPU::Z80::Assembler Data::Dump Data::HexDump File::Path List::Uniq Modern::Perl Object::Tiny::RW Regexp::Common Test::Harness Text::Diff Text::Table YAML::Tiny
	eval $(perl -I "$srcdir/perl5/lib/perl5/" -Mlocal::lib)
}

build() {
	cd "$srcdir/z88dk"
	export BUILD_SDCC=1 BUILD_SDCC_HTTP=1
	./build.sh
}

package() {
	cd "$srcdir/z88dk"
	PREFIX="$pkgdir/usr/local" make install
}
```

Since the environment is kept for each function run, you only need to run this once in the prepare function and you can remove it from everywhere else.

2023-10-16 17:45 UTC, Elara6331 commented on z88dk-git/lure.sh
> +	eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
Remove this (as mentioned before)

```suggestion
```

2023-10-16 17:45 UTC, Elara6331 commented on z88dk-git/lure.sh
>  	PREFIX="$pkgdir/usr/local" make install
Since this is a package and not a manual install, use `/usr` instead of `/usr/local`

```suggestion
	PREFIX="$pkgdir/usr" make install
```

2023-10-16 17:45 UTC, Elara6331 commented on z88dk-git/lure.sh
> +sources=('git+https://github.com/z88dk/z88dk?~recursive=true&~rev=e89d1b4477687747b500fbe0e25fc52fe35056a7')
Do you need to specify a commit here? Generally, git packages should get the latest source unless it's broken or can't be built.

2023-10-17 00:05 UTC, atirut-w commented on z88dk-git/lure.sh
>  	PREFIX="$pkgdir/usr/local" make install
The compiler seems to hardcode its config in that directory, so nothing can be done as of now. I'll investigate and see if this is a problem with LURe or Z88DK.

2023-10-17 00:07 UTC, atirut-w commented on z88dk-git/lure.sh
> +sources=('git+https://github.com/z88dk/z88dk?~recursive=true&~rev=e89d1b4477687747b500fbe0e25fc52fe35056a7')
Z88DK tend to have commits that won't build or are straight up broken. I'm not sure if there are other options.

2023-10-17 00:08 UTC, Elara6331 commented on z88dk-git/lure.sh
> +sources=('git+https://github.com/z88dk/z88dk?~recursive=true&~rev=e89d1b4477687747b500fbe0e25fc52fe35056a7')
Alright, that's fine then

2023-10-24 00:10 UTC, Elara6331 commented on z88dk-git/lure.sh
>  	PREFIX="$pkgdir/usr/local" make install
Based on the issue you created in the z88dk repo, you should be able to fix this by putting `PREFIX="/usr" DESTDIR="$pkgdir"` before both `./build.sh` and `make install`. I tried it and I was able to successfully compile a C file with `zcc`.

2023-10-24 02:33 UTC, atirut-w commented on z88dk-git/lure.sh
>  	PREFIX="$pkgdir/usr/local" make install
I completely forgot to complete this PR. Sorry for the wait, your suggestions worked like a charm.

2023-10-24 02:34 UTC, Elara6331 approved these changes
Thanks, merging now :)

2023-10-24 02:35 UTC, merged